### PR TITLE
Syscall as constants per archname instead of requiring syscall.ph

### PR DESCRIPTION
**Pull request by dolmen**
This is the implementation of my suggestion at:
http://www.nntp.perl.org/group/perl.cpan.testers.discuss/2017/02/msg3995.html

Note: I've not been able to properly test this fix as the test suite is doesn't test the `getdents` function.

### CODE REVIEW

**Comment by glasswalk3r** [comment]
Thank you Olivier!
I pulled your changes to a new branch that I'm evaluating (added some tests over there if you want to take a look).
I'm not comfortable having those values hard coded, but for now it is better than having to rely on `h2ph`, even though it will fail for smokers in ARM.
I'm considering using `Inline::C` to get the `SYS_getdents` setup correctly during the distribution install, that should take of compatibility problems.

**Comment by dolmen** [comment]
> I'm not comfortable having those values hard coded, but for now it is better than having to rely on h2ph, even though it will fail for smokers in ARM.

Use the power of CPAN testers: just add a test in your testsuite that will extract the real value for the syscall (for example with a `grep -R getdents /usr/include`) and report the result so you will have the value in testers reports. Even if you have to add 10 values manually it will be much less work than writing a Makefile.PL that uses Inline::C.

**Comment by dolmen** [comment]
The test could give the output of this command:
```sh
echo -e '#include <syscall.h>\nSYS_getdents' | cpp -P
```

**Comment by glasswalk3r** [comment]
> The test could give the output of this command:
> `echo -e '#include <syscall.h>\nSYS_getdents' | cpp -P`

That's a nice hack!
I just release 0.002 to CPAN using `Inline::C` to get the C constant, I wasn't aware I could get this from a simple command in the shell. Anyway, I'm expecting to get all tests as PASS on Linux with 0.0002 since I'm not using hard codes anymore.
I'm working on release 0.003 to not use Inline::C inside the distribution, but in the Makefile.PL itself by using `Dist::Zilla::Plugin::MakeMaker::Awesome`.
On the other hand, I'm thinking about using Inline::C a bit more: currently, the functions exported by `Linux::NFS::BigDir` are slower than `readdir` on a local file system. Even though that is not the main objective of the distribution (they should be faster on NFS), I think getting closer to `readdir` would be a plus. I did some profiling, and I'm getting a lot of calls to `unpack` (of course, I can't avoid that). If I do things directly in C and got back the results by the XS provided by Inline::C, I suppose I can get a better performance.

**Pull request closed without merging**
